### ISSUE TITLE
Publishing record creates an error, if 'dates' are set

### ISSUE THREAD

**Issue by JoshBone** [BlinkenOSA/clockwork#72]
```
[2018-07-20 06:51:09,997: ERROR/ForkPoolWorker-4] Task index_add_finding_aids[4a842c97-5f3a-4e2b-a6f9-9aace7c0d004] raised unexp
ected: KeyError('dates',)
Traceback (most recent call last):
  File "/opt/ams/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/ams/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/ams/clockwork/finding_aids/tasks.py", line 13, in index_add_finding_aids
    indexer.prepare_index()
  File "/opt/ams/clockwork/finding_aids/indexer.py", line 25, in prepare_index
    self._make_json()
  File "/opt/ams/clockwork/finding_aids/indexer.py", line 180, in _make_json
    j["dates"].append(
KeyError: 'dates'
```

**Comment by JoshBone** [comment]
```
[2018-07-23 15:01:34,383: ERROR/ForkPoolWorker-9] Task index_add_finding_aids[a11ea41f-8223-4e55-a315-15490d9131ce] raised unexpected: UnicodeDecodeError('ascii', '<Person: Hal\xc3\xa1sz, P\xc3\xa9ter> is not JSON serializable', 12, 13, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/opt/ams/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 388, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/opt/ams/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 330, in on_error
    task, request, eager=eager, call_errbacks=call_errbacks,
  File "/opt/ams/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 164, in handle_error_state
    call_errbacks=call_errbacks)
  File "/opt/ams/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 209, in handle_failure
    call_errbacks=call_errbacks,
  File "/opt/ams/env/local/lib/python2.7/site-packages/celery/backends/base.py", line 163, in mark_as_failure
    traceback=traceback, request=request)
  File "/opt/ams/env/local/lib/python2.7/site-packages/celery/backends/base.py", line 307, in store_result
    result = self.encode_result(result, state)
  File "/opt/ams/env/local/lib/python2.7/site-packages/celery/backends/base.py", line 297, in encode_result
    return self.prepare_exception(result)
  File "/opt/ams/env/local/lib/python2.7/site-packages/celery/backends/base.py", line 240, in prepare_exception
    return {'exc_type': type(exc).__name__, 'exc_message': string(exc)}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
```
